In [1]:
import torch
print(torch.__version__)

2.0.1+cu117


In [2]:
x = torch.Tensor([5,4]) #tensor is like an array 
y = torch.Tensor([6,2])

print(x*y)

tensor([30.,  8.])


In [3]:
x=torch.zeros([3,4])

print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
y = torch.rand([3,4])
y

tensor([[0.1456, 0.2789, 0.2985, 0.8124],
        [0.8630, 0.2742, 0.6668, 0.8946],
        [0.2075, 0.1466, 0.6329, 0.8539]])

In [5]:
#reshaping in pytorch
y= y.view([1,12])
y 

tensor([[0.1456, 0.2789, 0.2985, 0.8124, 0.8630, 0.2742, 0.6668, 0.8946, 0.2075,
         0.1466, 0.6329, 0.8539]])