In [1]:
import torch
print(torch.__version__)

2.0.1+cu117


In [2]:
x = torch.Tensor([5,4]) #tensor is like an array 
y = torch.Tensor([6,2])

print(x*y)

tensor([30.,  8.])


In [3]:
x=torch.zeros([3,4])

print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [4]:
y = torch.rand([3,4])
y

tensor([[0.1456, 0.2789, 0.2985, 0.8124],
        [0.8630, 0.2742, 0.6668, 0.8946],
        [0.2075, 0.1466, 0.6329, 0.8539]])

In [5]:
#reshaping in pytorch
y= y.view([1,12])
y 

tensor([[0.1456, 0.2789, 0.2985, 0.8124, 0.8630, 0.2742, 0.6668, 0.8946, 0.2075,
         0.1466, 0.6329, 0.8539]])

In [2]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR
# Check number of dimensions for TENSOR
TENSOR.ndim
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])

In [3]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(1,4, 3))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[[0.5264, 0.1095, 0.2844],
          [0.3372, 0.5516, 0.3468],
          [0.1875, 0.7424, 0.4901],
          [0.1455, 0.7136, 0.6904]]]),
 torch.float32,
 3)

In [4]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(4, 3,1))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[[0.4873],
          [0.5684],
          [0.5403]],
 
         [[0.7774],
          [0.3888],
          [0.4756]],
 
         [[0.1788],
          [0.8944],
          [0.9538]],
 
         [[0.0752],
          [0.6396],
          [0.2398]]]),
 torch.float32,
 3)

In [5]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [7]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [8]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [9]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [10]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

#torch.matmul(tensor_A, tensor_B) # (this will error)
output_1 = torch.matmul(tensor_A, tensor_B.T)
print(output_1) 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])


In [11]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=7) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input: \n{x}Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input: 
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.0554,  1.0336,  0.6755,  0.5908, -0.7443,  1.0595,  0.3882],
        [ 4.3104,  2.0014,  0.6511,  0.7328, -0.5351,  2.5535,  1.6245],
        [ 6.5654,  2.9692,  0.6266,  0.8749, -0.3259,  4.0474,  2.8609]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 7])


In [12]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
#print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [16]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [19]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100, 10)
tensor.dtype

torch.float32

In [20]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [21]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [22]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [23]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [26]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [27]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [44]:
# Create a tensor 
import torch
x = torch.arange(1, 10).view(3, 3)
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [45]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[1][2]}") 
#print(f"Third square bracket: {x[0][2][2]}")|

First square bracket:
tensor([1, 2, 3])
Second square bracket: 6
